"""baseline integration tests using the real synthetic speaker assets.

These run the full in-process pipeline (`main.run_pipeline`) against the
deterministic assets generated by scripts/build_test_assets.py. The assets
carry real detected faces with animated mouths and real synthesized speech
(ffmpeg flite), so MediaPipe + Silero VAD jointly drive active-speaker
selection. Tests skip when an asset is not present (they are gitignored).
"""

import json
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import main
from src.config import load_config

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(PROJECT_ROOT, "test_assets")

CONFIG = load_config(os.path.join(PROJECT_ROOT, "config.yaml"))


def asset_path(name):
    return os.path.join(ASSETS, f"{name}.mp4")


def run_asset(name, tmp_path, analysis_only=True):
    """Run the pipeline over an asset and return the parsed timeline."""
    out = os.path.join(str(tmp_path), "out.mp4")
    result = main.run_pipeline(
        asset_path(name),
        out,
        CONFIG,
        analysis_only=analysis_only,
    )
    with open(result["timeline_path"], "r", encoding="utf-8") as fh:
        return json.load(fh), result


def require_asset(name):
    return os.path.isfile(asset_path(name))


# ---------------------------------------------------------------------------
# A. Single speaker: one face speaking the whole time.
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not require_asset("single_speaker_speech"), reason="asset absent")
def test_single_speaker_locks_active_speaker(tmp_path):
    timeline, result = run_asset("single_speaker_speech", tmp_path)
    frames = timeline["frames"]
    ids_set = {f["active_speaker_id"] for f in frames}
    assert ids_set <= {"face_1", None}
    assert "face_1" in ids_set
    # The face should be the selected speaker for the majority of the run
    # (allow warm-up frames at the very start, but never a switch).
    locked = [f for f in frames if f["active_speaker_id"] == "face_1"]
    assert len(locked) >= len(frames) * 0.7
    assert result["switch_events"] == 0


# ---------------------------------------------------------------------------
# B. Two speakers alternating: A -> B -> A with switch events.
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not require_asset("two_speakers"), reason="asset absent")
def test_two_speakers_switch_events(tmp_path):
    timeline, result = run_asset("two_speakers", tmp_path)
    frames = timeline["frames"]
    ids_seen = [f["active_speaker_id"] for f in frames]
    assert result["switch_events"] >= 2
    # Both speakers selected at some point.
    assert "face_1" in ids_seen and "face_2" in ids_seen


# ---------------------------------------------------------------------------
# C. Silence: static face with silent audio => no speaker ever selected.
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not require_asset("silence_speaker"), reason="asset absent")
def test_silence_no_speaker(tmp_path):
    timeline, result = run_asset("silence_speaker", tmp_path)
    frames = timeline["frames"]
    for f in frames:
        assert f["active_speaker_id"] is None
        assert f["is_fallback"] is True
        assert f["fallback_reason"] in ("no_speech",)


# ---------------------------------------------------------------------------
# D. Face loss: speaker disappears for 2s (face track lost) then recovers.
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not require_asset("face_loss"), reason="asset absent")
def test_face_loss_reports_track_lost_and_recovers(tmp_path):
    timeline, result = run_asset("face_loss", tmp_path)
    frames = timeline["frames"]
    reasons = {f["fallback_reason"] for f in frames}
    assert "face_track_lost" in reasons
    assert "no_visible_face" not in reasons, (
        "Once a speaker is locked the whole absence should report track lost"
    )
    ids_seen = {f["active_speaker_id"] for f in frames}
    assert None in ids_seen
    # The speaker re-locks after the gap (new track, but a speaker exists).
    assert any(x is not None for x in ids_seen)


# ---------------------------------------------------------------------------
# E. Off-screen speech: two static faces, speech from nobody visible.
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not require_asset("off_screen_speech"), reason="asset absent")
def test_off_screen_speech_no_selection(tmp_path):
    timeline, result = run_asset("off_screen_speech", tmp_path)
    frames = timeline["frames"]
    for f in frames:
        # No mouth motion => either no speech or low-confidence fallback.
        assert f["active_speaker_id"] is None
        assert f["is_fallback"] is True
        assert f["fallback_reason"] in ("no_speech", "low_active_speaker_confidence")


# ---------------------------------------------------------------------------
# F. No face at all: speech present but no visible speaker.
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not require_asset("no_face_speech"), reason="asset absent")
def test_no_face_speech_fallback(tmp_path):
    timeline, result = run_asset("no_face_speech", tmp_path)
    frames = timeline["frames"]
    for f in frames:
        assert f["active_speaker_id"] is None
        assert f["fallback_reason"] == "no_visible_face"


# ---------------------------------------------------------------------------
# Auxiliary checks on the timeline schema for the assets.
# ---------------------------------------------------------------------------

@pytest.mark.skipif(
    not require_asset("single_speaker_speech"), reason="asset absent"
)
def test_timeline_schema_has_phase2_fields(tmp_path):
    _, result = run_asset("single_speaker_speech", tmp_path)
    with open(result["timeline_path"], "r", encoding="utf-8") as fh:
        data = json.load(fh)
    meta = data["meta"]
    assert meta["speaker_strategy"] == "active_speaker_fusion_vad"
    frame = data["frames"][0]
    for key in (
        "audio_speech_probability",
        "mouth_motion_score",
        "active_speaker_score",
        "active_speaker_confidence",
        "speaker_switch_event",
        "fallback_reason",
    ):
        assert key in frame


@pytest.mark.skipif(
    not require_asset("single_speaker_speech"), reason="asset absent"
)
def test_audio_preserved_when_rendering(tmp_path):
    """Full render must preserve the audio track (silence or speech)."""
    timeline, result = run_asset("single_speaker_speech", tmp_path, analysis_only=False)
    assert os.path.isfile(os.path.join(str(tmp_path), "out.mp4"))
    import subprocess

    probe = subprocess.run(
        [
            "ffprobe", "-v", "error",
            "-select_streams", "a",
            "-show_entries", "stream=codec_type",
            "-of", "csv=p=0",
            os.path.join(str(tmp_path), "out.mp4"),
        ],
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert "audio" in probe.stdout